#!/bin/bash
# For CentOS installation

# CentOS update
echo "--> Updating CentOS system..."
sudo yum -y update
echo "--> CentOS system updated."

# CentOS upgrade
echo "--> Upgrading CentOS system..."
sudo yum -y upgrade
echo "--> CentOS system upgraded."

# CentOS configuration tool
echo "--> Installing CentOS configuration tools..."
sudo yum -y install yum-utils device-mapper-persistent-data lvm2
echo "--> CentOS configuration tools installed."

# Docker download and install
echo "--> Installing Docker..."
echo "----> Downloading docker dependencies"
sudo yum-configuration-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
echo "----> Docker dependencies downloaded."
echo "----> Performing installation..."
sudo yum install docker-ce
echo "----> Installation complete."
echo "----> Starting Docker service..."
sudo systemctl start docker
echo "----> Docker service running."
echo "--> Docker installation complete."

echo "--> Setup complete."

